[tool.poetry]
name = "project5"
version = "0.1.0"
description = ""
authors = ["Ekaterina Nekhoroshkova <e_nekhoroshkova95@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
